# Generated by Django 2.0b1 on 2017-10-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(verbose_name='TheMovieDB ID Number')),
                ('name', models.CharField(max_length=200, verbose_name='Show title')),
                ('slug', models.SlugField(blank=True, max_length=40)),
                ('episodes', models.IntegerField(blank=True)),
                ('seasons', models.IntegerField(blank=True)),
                ('overview', models.TextField()),
                ('imported', models.DateField(blank=True, null=True, verbose_name='First imported')),
            ],
        ),
    ]
