# Generated by Django 2.0b1 on 2017-10-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='language',
            field=models.CharField(blank=True, max_length=50, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='show',
            name='episodes',
            field=models.IntegerField(blank=True, verbose_name='Number of episodes'),
        ),
        migrations.AlterField(
            model_name='show',
            name='overview',
            field=models.TextField(blank=True, verbose_name='General overview'),
        ),
        migrations.AlterField(
            model_name='show',
            name='seasons',
            field=models.IntegerField(blank=True, verbose_name='Number of seasons'),
        ),
        migrations.AlterField(
            model_name='show',
            name='slug',
            field=models.SlugField(max_length=40, verbose_name='URL shortcut'),
        ),
    ]
