# Generated by Django 2.0b1 on 2017-10-30 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20171030_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airdate', models.DateField(blank=True, verbose_name='Episode airdate')),
                ('name', models.CharField(max_length=200, verbose_name='Episode name')),
                ('overview', models.TextField(blank=True, verbose_name='Episode overview')),
                ('episode_number', models.IntegerField(verbose_name='Episode number')),
                ('seen', models.BooleanField(default=False, verbose_name='Seen this episode?')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Season title')),
                ('season_number', models.IntegerField(verbose_name='Season number')),
                ('airdate', models.DateField(blank=True, verbose_name='Season kickoff')),
                ('overview', models.TextField(blank=True, verbose_name='Season overview')),
                ('seen', models.BooleanField(default=False, verbose_name='Seen this season?')),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='Seen this show?'),
        ),
        migrations.AddField(
            model_name='season',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.Show'),
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.Season'),
        ),
    ]
