# Generated by Django 2.0b1 on 2017-10-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_auto_20171030_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='screenshot',
            field=models.URLField(blank=True, verbose_name='Episode screenshot URL'),
        ),
        migrations.AddField(
            model_name='season',
            name='season_poster',
            field=models.URLField(blank=True, verbose_name='Season poster URL'),
        ),
        migrations.AddField(
            model_name='show',
            name='bg_art',
            field=models.URLField(blank=True, verbose_name='Background art URL'),
        ),
    ]
