# Generated by Django 2.0b1 on 2017-10-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_auto_20171030_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='airdate',
            field=models.DateField(null=True, verbose_name='Episode airdate'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='overview',
            field=models.TextField(null=True, verbose_name='Episode overview'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='screenshot',
            field=models.URLField(null=True, verbose_name='Episode screenshot URL'),
        ),
        migrations.AlterField(
            model_name='season',
            name='airdate',
            field=models.DateField(null=True, verbose_name='Season kickoff'),
        ),
        migrations.AlterField(
            model_name='season',
            name='overview',
            field=models.TextField(null=True, verbose_name='Season overview'),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_poster',
            field=models.URLField(null=True, verbose_name='Season poster URL'),
        ),
        migrations.AlterField(
            model_name='show',
            name='bg_art',
            field=models.URLField(null=True, verbose_name='Background art URL'),
        ),
        migrations.AlterField(
            model_name='show',
            name='episodes',
            field=models.IntegerField(null=True, verbose_name='Number of episodes'),
        ),
        migrations.AlterField(
            model_name='show',
            name='imported',
            field=models.DateField(null=True, verbose_name='First imported'),
        ),
        migrations.AlterField(
            model_name='show',
            name='language',
            field=models.CharField(max_length=50, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='show',
            name='overview',
            field=models.TextField(null=True, verbose_name='General overview'),
        ),
        migrations.AlterField(
            model_name='show',
            name='seasons',
            field=models.IntegerField(null=True, verbose_name='Number of seasons'),
        ),
    ]
